// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_service.proto

#include "file_service.pb.h"
#include "file_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace pb {

static const char* LaptopService_method_names[] = {
  "/pb.LaptopService/UploadFile",
};

std::unique_ptr< LaptopService::Stub> LaptopService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LaptopService::Stub> stub(new LaptopService::Stub(channel));
  return stub;
}

LaptopService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_UploadFile_(LaptopService_method_names[0], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::pb::UploadFileRequest>* LaptopService::Stub::UploadFileRaw(::grpc::ClientContext* context, ::pb::UploadFileResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::pb::UploadFileRequest>::Create(channel_.get(), rpcmethod_UploadFile_, context, response);
}

void LaptopService::Stub::experimental_async::UploadFile(::grpc::ClientContext* context, ::pb::UploadFileResponse* response, ::grpc::experimental::ClientWriteReactor< ::pb::UploadFileRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::pb::UploadFileRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::pb::UploadFileRequest>* LaptopService::Stub::AsyncUploadFileRaw(::grpc::ClientContext* context, ::pb::UploadFileResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::pb::UploadFileRequest>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::pb::UploadFileRequest>* LaptopService::Stub::PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::pb::UploadFileResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::pb::UploadFileRequest>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, false, nullptr);
}

LaptopService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LaptopService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< LaptopService::Service, ::pb::UploadFileRequest, ::pb::UploadFileResponse>(
          [](LaptopService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::pb::UploadFileRequest>* reader,
             ::pb::UploadFileResponse* resp) {
               return service->UploadFile(ctx, reader, resp);
             }, this)));
}

LaptopService::Service::~Service() {
}

::grpc::Status LaptopService::Service::UploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::pb::UploadFileRequest>* reader, ::pb::UploadFileResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pb

